services:

  db:
    build:
      context: ./docker    #path to Dockerfile
    container_name: moviedb_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: moviedb
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql    #path to init.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .     #path to Dockerfile
    container_name: moviedb_app
    depends_on:
      - db
    command: sh -c "sleep 3 && python main.py"
    volumes:
      - ./.env:/app/.env
    tty: true
